# SPDX-FileCopyrightText: 2024 EfficiOS Inc.
#
# SPDX-License-Identifier: MIT

[tool.black]
  include = '''
  (
       \.pyi?$
     | \.py\.in$
  )
  '''
  exclude = '''
  (
       src/bindings/python/bt2/build/
     | src/bindings/python/bt2/setup\.py$
     | src/bindings/python/bt2/bt2/native_bt\.py$
     | src/bindings/python/bt2/bt2/version\.py$
     | tests/utils/python/normand\.py$
     | tests/utils/python/typing/typing\.py$
     | tests/utils/python/tap

  )
  '''

[tool.isort]
profile = "black"
extend_skip_glob = [
    "tests/utils/python/tap",
    "tests/utils/python/normand.py",
    "tests/utils/python/typing/typing.py",
]
length_sort = true

[tool.pyright]
reportPrivateUsage = false
